### PR TITLE
Add parameter to the hook useGoogleAnalytics to tell whether or not we can create cookies

### LINKED ISSUE #17: Just having the addon on a portal should not create cookies
If I have `volto-google-analytics` installed on a portal, cookies are created without even calling `useGoogleAnalytics`. For GDPL reasons, cookies should not be created in this situation, as we need to obtain the user's consent first.

Cookies are created when [initializing GA](https://github.com/collective/volto-google-analytics/blob/33496e25666ef75d3e0f5fec1e7942cc42f7e2de/src/index.js#L11-L38). So I propose that this code stays inside a function, to be called explicitly.

### PR DESCRIPTION
**Pull request by wesleybl**
On portals that need to follow GDPL, cookies can only be created after the user's consent. Then add the
parameter to control whether or not we create the cookie.

Fixes #17

### CODE REVIEW

**Comment by giuliaghisini** [comment]
> We initialize GA explicitly so that no cookie is generated when installing the addon on a portal. On portals that need to follow GDPL, cookies can only be created after the user's consent.
> 
> We created the initializeGA function to initialize GA.
> 
> Fixes #17

Ok, so as i can see no changes are needed for previous addon-installations if i update the addon.. right?

**Comment by wesleybl** [comment]
@giuliaghisini this is a breaking change. Now it is necessary to call the [initializeGA](https://github.com/collective/volto-google-analytics/blob/d790999bce2f814925c9546ad9dfe6a9f62f39af/src/index.js#L11) function explicitly, before calling 
`useGoogleAnalytics`. I put this in the example:

https://github.com/collective/volto-google-analytics/pull/18/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5

I will create an "Upgrading from 2.x to 3.x" section in the Readme, saying this.

**Comment by wesleybl** [comment]
@giuliaghisini I changed the implementation to not be a breaking change. Now we have a parameter in the `useGoogleAnalytics` hook, which says whether or not we can create the cookie. The default for this parameter is `true`. So current installations will not be affected.

Can you take a look please?

**Review by giuliaghisini — APPROVED** [review]

**Comment by wesleybl** [comment]
@giuliaghisini can we merge this PR and make a release?

**Review by giuliaghisini — APPROVED** [review]

**Comment by giuliaghisini** [comment]
> @giuliaghisini can we merge this PR and make a release?

released 2.1.0

**Comment by wesleybl** [comment]
Thanks!

**Pull request merged**
